batch_size: 16
cache_path: null
center_max_distance: 30
config: null
cross_cutoff_bias: 40
cross_cutoff_weight: 3
cross_distance_embed_dim: 32
cross_max_distance: 80
cudnn_benchmark: true
data_dir: null
dihediral_dim: 4
distance_embed_dim: 32
dropout: 0.0
dynamic_max_cross: true
edge_feature_dim: 103
ema_rate: 0.999
embedding_scale: 10000
embedding_type: sinusoidal
esm_embeddings_path_test: null
esm_embeddings_path_train: data/splits_time/lm_embeddings_chains_train_short.pt
esm_embeddings_path_val: null
esm_embeddings_peptide_test: null
esm_embeddings_peptide_train: null
esm_embeddings_peptide_val: null
gpu: 0
inference_earlystop_goal: max
inference_earlystop_metric: valinf_rmsds_backbone_lt2
inference_steps: 20
intra_dim: 5
log_dir: null
lr: 0.001
max_radius: 5.0
n_epochs: 850
no_batch_norm: false
ns: 48
num_conv_layers: 4
num_dataloader_workers: 0
num_gpu: 3
num_inference_complexes: 200
nv: 10
pep_amino_dim: 104
pin_memory: true
rec_amino_dim: 22
restart_dir: null
restart_lr: 0.001
rot_sigma_max: 1.65
rot_sigma_min: 0.03
rot_weight: 0.25
run_name: rapidock_local
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 50
sigma_embed_dim: 32
split_test: null
split_train: null
split_val: null
test_sigma_intervals: true
top_k: 24
tor_backbone_sigma_max: 3.14
tor_backbone_sigma_min: 0.0314
tor_backbone_weight: 0.25
tor_sidechain_sigma_max: 3.14
tor_sidechain_sigma_min: 0.0314
tor_sidechain_weight: 0.25
tr_sigma_max: 30
tr_sigma_min: 0.1
tr_weight: 0.25
use_ema: true
use_second_order_repr: false
val_inference_freq: 20
w_decay: 0.0
